# Generated by Django 3.1.5 on 2021-02-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True, verbose_name='catégorie')),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'catégories de produits',
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True, verbose_name='unité')),
                ('abbreviation', models.CharField(max_length=191, unique=True, verbose_name='unité abbrégée')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True, verbose_name='produit alimentaire')),
                ('description', models.TextField(blank=True, verbose_name='description des produits')),
                ('pu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avaible', models.BooleanField(default=True)),
                ('packing', models.PositiveIntegerField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epicomm.categorie')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epicomm.unite')),
            ],
            options={
                'verbose_name_plural': 'produits alimentaires',
                'ordering': ['name'],
            },
        ),
    ]
