# Generated by Django 3.1.5 on 2021-02-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epicomm.categorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='epicomm.unite'),
        ),
    ]
