# Generated by Django 3.1.5 on 2021-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0002_auto_20210214_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='icone.svg', upload_to=''),
        ),
    ]
