# Generated by Django 3.1.5 on 2021-02-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0003_product_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='icon',
            field=models.ImageField(upload_to='static/epicomm/icons'),
        ),
    ]
