# Generated by Django 3.1.5 on 2021-02-15 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0006_auto_20210215_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandline',
            options={'verbose_name': "Ligne de commande d'un produit", 'verbose_name_plural': "Lignes de commande d'un produit"},
        ),
        migrations.AlterModelOptions(
            name='commanduser',
            options={'verbose_name': 'Commande individuelle', 'verbose_name_plural': 'Commandes individuelles'},
        ),
        migrations.AddField(
            model_name='commandline',
            name='commandUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epicomm.commanduser'),
        ),
        migrations.AddField(
            model_name='commandline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epicomm.product'),
        ),
        migrations.AddField(
            model_name='commandline',
            name='qtt',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commanduser',
            name='products',
            field=models.ManyToManyField(through='epicomm.CommandLine', to='epicomm.Product'),
        ),
    ]
