# Generated by Django 3.1.5 on 2021-02-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0008_auto_20210215_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanduser',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
