# Generated by Django 3.1.5 on 2021-02-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0009_auto_20210215_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandmain',
            name='products',
            field=models.ManyToManyField(to='epicomm.Product'),
        ),
        migrations.AlterField(
            model_name='commanduser',
            name='collected',
            field=models.BooleanField(verbose_name='emmenée'),
        ),
        migrations.AlterField(
            model_name='commanduser',
            name='paid',
            field=models.BooleanField(verbose_name='payée'),
        ),
    ]
