# Generated by Django 3.1.5 on 2021-02-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0010_auto_20210216_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandmain',
            name='closed_at',
            field=models.DateField(null=True, verbose_name='fermée le '),
        ),
    ]
