# Generated by Django 3.1.5 on 2021-02-16 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epicomm', '0014_auto_20210216_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtt', models.PositiveIntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epicomm.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Produit avec quantité d'un utilisateur",
                'verbose_name_plural': "Produits avec quantité d'un utilisateur",
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='créée le ')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('paid', models.BooleanField(verbose_name='payée')),
                ('collected', models.BooleanField(verbose_name='emmenée')),
                ('item', models.ManyToManyField(to='epicomm.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande individuelle',
                'verbose_name_plural': 'Commandes individuelles',
            },
        ),
        migrations.RenameModel(
            old_name='CommandMain',
            new_name='Commande',
        ),
        migrations.RemoveField(
            model_name='commanduser',
            name='commandLine',
        ),
        migrations.RemoveField(
            model_name='commanduser',
            name='user',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icon',
            field=models.ImageField(default='default.svg', upload_to='epicomm'),
        ),
        migrations.DeleteModel(
            name='CommandLine',
        ),
        migrations.DeleteModel(
            name='CommandUser',
        ),
    ]
