# Generated by Django 3.1.5 on 2021-02-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0015_auto_20210216_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande globale', 'verbose_name_plural': 'Commandes globales'},
        ),
    ]
