# Generated by Django 3.1.5 on 2021-02-18 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0017_remove_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epicomm.panier'),
        ),
        migrations.AddField(
            model_name='panier',
            name='items',
            field=models.ManyToManyField(through='epicomm.Item', to='epicomm.Product'),
        ),
    ]
