# Generated by Django 3.1.5 on 2021-02-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0018_auto_20210218_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='commande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epicomm.commande'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='collected',
            field=models.BooleanField(default=False, verbose_name='emmenée'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='payée'),
        ),
    ]
