# Generated by Django 3.1.5 on 2021-02-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0019_auto_20210218_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='delivered_at',
            field=models.DateField(blank=True, null=True, verbose_name='livrée le '),
        ),
    ]
