# Generated by Django 3.1.5 on 2021-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0020_auto_20210218_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='name',
            field=models.CharField(max_length=191, unique_for_date='created_at', verbose_name='commande'),
        ),
    ]
