# Generated by Django 3.1.5 on 2021-02-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0021_auto_20210218_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
