# Generated by Django 3.1.5 on 2021-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0023_auto_20210219_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='coût du transport'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='cloturée'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='livrée'),
        ),
    ]
