# Generated by Django 3.1.5 on 2021-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicomm', '0024_auto_20210220_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avaible',
        ),
        migrations.AlterField(
            model_name='commande',
            name='products',
            field=models.ManyToManyField(to='epicomm.Product', verbose_name='produits'),
        ),
    ]
