# Generated by Django 3.1.5 on 2021-02-23 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epicomm', '0025_auto_20210220_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panier',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commande individuelle', 'verbose_name_plural': 'Commandes individuelles'},
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epicomm.product', verbose_name='produit'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='collected',
            field=models.BooleanField(default=False, verbose_name='récupérée'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='montant de la commande'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
